### ISSUE TITLE
suggestion: cancel auto-walk when w or s is pressed

### ISSUE THREAD

**Issue by AndrielChaoti** [Dupernite/DuperAutoWalk#1]
title.

if possible make it so that auto-walking is cancelled when the walk forward or backward keys are pressed (key down events)?

makes cancelling auto-walk a lot easier, but still allows strafing/turning inputs to keep walking and dodge obstacles.

(this is generally how auto-walk works in other games where it exists.)

**Comment by Dupernite** [comment]
the way I made the auto walking, pressing W to stop wouldn't work, but maybe clicking S to stop could work, I'll try it and maybe publish an update by tomorrow

**Comment by Dupernite** [comment]
Updated the mod, thanks for the suggestion
